###########################
# Stage 1 Build Angular
###########################

FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

###########################
# Stage 2 Nginx
###########################

FROM nginx:alpine

COPY nginx.conf /etc/nginx/nginx.conf

COPY --from=build \
     /app/dist/angular-nginx/browser \
     /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
