worker_processes auto;

events {
    worker_connections 1024;
}

http {

    include /etc/nginx/mime.types;

    ##################################################
    # Rate Limiting
    ##################################################

    limit_req_zone $binary_remote_addr
                   zone=api_limit:10m
                   rate=5r/s;

    server {

        listen 80;

        root /usr/share/nginx/html;
        index index.html;

        ##################################################
        # Angular Static Files
        ##################################################

        location / {

            try_files $uri $uri/ /index.html;
        }

        ##################################################
        # Static Asset Caching
        ##################################################

        location ~* \.(js|css|png|jpg|jpeg|gif|svg|woff|woff2)$ {

            expires 30d;

            add_header Cache-Control "public, max-age=2592000";

            access_log off;
        }

        ##################################################
        # Rate Limited API
        ##################################################

        location /api {

            limit_req zone=api_limit burst=10 nodelay;

            return 200 "API Request Successful";
        }
    }
}
